---
version: '3'
services:
  download-data:
    image: freqtradeorg/freqtrade:develop
    container_name: download-data
    volumes:
      - ".:/freqtrade/user_data/data"
    command: >
      download-data
      --timerange ${START_DATE:-20201201}-${END_DATE:-20211001}
      --timeframe 1m 3m 5m 15m 30m 1h 2h 4h 1d
      --datadir user_data/data/${EXCHANGE:-bybit}
      --config user_data/data/pairlists.json
      --config user_data/data/${EXCHANGE:-bybit}-usdt-static.json
