name: Update Data Bybit

on: [push,workflow_dispatch]

concurrency: 1

jobs:

  Download-Exchange-Data:
    runs-on: ubuntu-latest
    timeout-minutes: 1800
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Prep Git
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git reset --hard HEAD
          git status

      - name: Bybit Backtesting Variables
        id: bybit-dates
        uses: falti/dotenv-action@v0.2.6
        with:
          log-variables: true
          path:
            backtesting-bybit.env

      - name: Download Bybit Data (${{ steps.bybit-dates.outputs.start_date }} - ${{ steps.bybit-dates.outputs.end_date }})
        id: bybit-data-download
        env:
          START_DATE: ${{ steps.bybit-dates.outputs.start_date }}
          END_DATE: ${{ steps.bybit-dates.outputs.end_date }}
          EXCHANGE: bybit
        run: |
          docker-compose run --rm download-data

      - name: Fix File Ownership
        run: |
          sudo chown -R $(id -u):$(id -g) .

      - name: Commit Bybit Changed Files
        id: commit-bybit-changes
        if: steps.bybit-data-download.outcome == 'success'
        continue-on-error: true
        run: |
          git add bybit/*.json.gz
          git commit -a -m "Update Bybit exchange data from ${{ steps.bybit-dates.outputs.start_date }} to ${{ steps.bybit-dates.outputs.end_date }}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        if: steps.commit-bybit-changes.outcome == 'success'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
